title: "ZZEROFINDD DFIR Blog"
description: "Incident Response & Digital Forensics"
baseurl: ""
url: "https://zzerofindd.github.io"


markdown: kramdown
highlighter: rouge

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "ZZEROFINDD"
      comments: true

categories:
  - Incident Response
  - Malware Analysis
  - Forensics
  - Web Attack
  - Case Study
